all: lsh HC

lsh:	
	g++ mainLSH.cpp LSH.cpp euclideanH.cpp cosineH.cpp gfunction.cpp ExactNN.cpp readFile.cpp -o lsh

HC:
	g++ mainHC.cpp HyperCube.cpp euclideanH.cpp cosineH.cpp gfunction.cpp ExactNN.cpp readFile.cpp -o HC

