recommendation:
	g++ mainRecc.cpp readCmdRec.cpp LSH.cpp HyperCube.cpp kmeans.cpp gfunction.cpp cosineH.cpp euclideanH.cpp simplefunctions.cpp recommendationFunctions.cpp -o recommendation

.PHONY: recommendation

